(package "indent-control"
         "0.3.4"
         "Management for indentation level")

(website-url "https://github.com/jcs-elpa/indent-control")
(keywords "control" "indent" "tab" "generic" "level")

(package-file "indent-control.el")

(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
